### ISSUE TITLE
Capri raises warnings due to wiki text used by Codebeamer

### ISSUE THREAD

**Issue by twodrops** [useblocks/sphinx-needs-enterprise#11]
The context area of codebeamer uses a wiki syntax which during sphinx-needs import raises following warnings due to incompatibility with rst Syntax.

>Inline strong start-string without end-string

> Inline emphasis start-string without end-string

> Anonymous hyperlink mismatch

**Comment by twodrops** [comment]
Strangely "Anonymous hyperlink mismatch" is raised as error and not warning. So not possible to ignore this as warning for now.

**Comment by twodrops** [comment]
Codebeamer allows to store the description as Wiki text or Plain text. If Plain text is used for storing there are no issues with capri, However the default is Wiki text.

![image](https://user-images.githubusercontent.com/103930/141980676-1cff1fcb-176e-46c2-bb3d-f61c913b17f7.png)
 
Hopefully there is also API to fetch the context as text.

**Comment by danwos** [comment]
Implemented with PR #15.

raw and wiki2html can be set for codebeamer based services.

For details take a look into http://useblocks.com/sphinx-needs-enterprise/services/codebeamer.html#raw
