### ISSUE TITLE
Make sphinx-needs-enterprise available in PyPI

### ISSUE THREAD

**Issue by twodrops** [useblocks/sphinx-needs-enterprise#14]
I tried to install Sphinx-Needs-Enterprise following the instructions here
https://useblocks.com/sphinx-needs-enterprise/installation.html#pypi

However sphinx-needs-enterprise does not seem to be available in PyPI

**Comment by twodrops** [comment]
@danwos  Thanks for releasing sphinx-needs-enterprise in PyPI. There is however a problem that sphinx-needs-enterprise has a hard dependency to Sphinx-Needs 0.7.2
https://github.com/useblocks/sphinx-needs-enterprise/blob/bedbb51e99b63999d612f7ae04d5a29c959c3884/pyproject.toml#L14

This makes is not usable with with sphinx-needs > 0.7.2

**Comment by danwos** [comment]
Argh...
Checked the deps and updated them.
0.1.1 is already out :)

Thanks for the hint.
